# environment
env = "dev"

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
name = "blog-test"
address = "127.0.0.1:1323"


[db]
db_name = "blog_test"
user_name = "root"
pwd  = "Shiyi20171228"
host = "127.0.0.1"
port = "3306"


[jwt]
sign_method = "HS256"
secret = "dfjalsdjflasd"
exp = 72  # 单位: hours
